Feature/us 26
emmanuelranone/AlkemyWallet pull request #18
Opened 2022-12-28 21:28 UTC by MatGP20

Added Controller, Service and interface of Account

![image](https://user-images.githubusercontent.com/78388067/209873928-7ed8f053-7c80-48ae-9b17-cc6c4825e27f.png)

2022-12-28 22:36 UTC, emmanuelranone reviewed
Si apruebo este pr, eliminamos el archivo appsettings.json

2022-12-28 22:37 UTC, emmanuelranone requested changes
Si apruebo este pr, eliminamos el archivo appsettings.json

2022-12-28 23:39 UTC, MatGP20 commented
No, solo que quite del trace es el appsetting.Development.Json y lo puse en gitIgnore, para que ahí podamos tener cada uno su conectionString sin que se suba al repositorio.

2022-12-29 12:49 UTC, emmanuelranone commented
No, así como está. Si apruebo el pr, se elimina el archivo del repositorio. Por otro lado, habíamos dicho que todavía no íbamos a agregarlo al git ignore, dado que aún vamos a seguir trabajando sobre el archivo.

2022-12-29 12:59 UTC, emmanuelranone approved these changes

2022-12-29 12:59 UTC, merged